In [3]:
from sklearn.datasets import load_iris

X, y = load_iris(return_X_y=True)
X.shape, y.shape


((150, 4), (150,))

In [9]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size = 0.2,
    stratify=y,
    random_state=0
)
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((120, 4), (30, 4), (120,), (30,))

In [11]:
import numpy as np
np.unique([1,1,2,1,2], return_counts=True)

(array([1, 2]), array([3, 2]))

In [14]:
np.unique(y, return_counts=True) ## 각 나온 숫자의 출현 횟수

(array([0, 1, 2]), array([50, 50, 50]))

In [19]:
unique_values_test, unique_values_cnt_test = np.unique(y_test, return_counts=True)
print(unique_values_test, unique_values_cnt_test)
print(unique_values_cnt_test/ y_test.size)

[0 1 2] [10 10 10]
[0.33333333 0.33333333 0.33333333]


0.3333333333333333

In [21]:
X_train, X_val, y_train, y_val = train_test_split(
    X_train, y_train,
    test_size=0.2,
    stratify=y_train,
    random_state=0
)
X_train.shape, X_test.shape, X_val.shape,

((76, 4), (30, 4), (20, 4))

In [36]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.metrics import accuracy_score

# 모델 생성
max_depth = 4
tree = DecisionTreeClassifier(max_depth=max_depth, random_state=0)

# 학습
tree.fit(X_train, y_train)

# 검증
# 추론
pred_train = tree.predict(X_train)
pred_val = tree.predict(X_val)
# 검증
train_acc = accuracy_score(y_train, pred_train)
val_acc = accuracy_score(y_val, pred_val)

In [37]:
print(f"max_depth: {max_depth}")
print("Train accuracy:", train_acc)
print("Validation accuracy:", val_acc)

max_depth: 4
Train accuracy: 1.0
Validation accuracy: 0.95


In [63]:
def sosu(n):
    if n == 1 or n == 0:
        return False
    for i in range(2, int(n**0.5)+1):
        if n % i == 0:
            return False
    return True

In [ ]:
import time
primes = [True for _ in range(1000001)]
for i in range(2, 1000001):
    if primes[i] == True:
        for j in range(i*2, 1000001, i):
            primes[j] = False

T = int(input())

for i in range(T):
    n = int(input())
    s = time.time()
    partition = 0
    for num in range(2, n // 2 + 1):
        if primes[num] and primes[n - num]:
            partition += 1
    e = time.time()
    print(e-s)
    print(partition)



4 2
6 2
8 2
10 2
12 2
14 2
16 2
18 2
20 2
22 2
24 2
26 2
28 2
30 2
32 2
34 2
36 2
38 2
40 2
42 2
44 2
46 2
48 2
50 2
52 2
54 2
56 2
58 2
60 2
62 2
64 2
66 2
68 2
70 2
72 2
74 2
76 2
78 2
80 2
82 2
84 2
86 2
88 2
90 2
92 2
94 2
96 2
98 2
100 2
102 2
104 2
106 2
108 2
110 2
112 2
114 2
116 2
118 2
120 2
122 2
124 2
126 2
128 2
130 2
132 2
134 2
136 2
138 2
140 2
142 2
144 2
146 2
148 2
150 2
152 2
154 2
156 2
158 2
160 2
162 2
164 2
166 2
168 2
170 2
172 2
174 2
176 2
178 2
180 2
182 2
184 2
186 2
188 2
190 2
192 2
194 2
196 2
198 2
200 2
202 2
204 2
206 2
208 2
210 2
212 2
214 2
216 2
218 2
220 2
222 2
224 2
226 2
228 2
230 2
232 2
234 2
236 2
238 2
240 2
242 2
244 2
246 2
248 2
250 2
252 2
254 2
256 2
258 2
260 2
262 2
264 2
266 2
268 2
270 2
272 2
274 2
276 2
278 2
280 2
282 2
284 2
286 2
288 2
290 2
292 2
294 2
296 2
298 2
300 2
302 2
304 2
306 2
308 2
310 2
312 2
314 2
316 2
318 2
320 2
322 2
324 2
326 2
328 2
330 2
332 2
334 2
336 2
338 2
340 2
342 2
344 2
346 2
348 2
350 2
352 2
3